version: 2.1

jobs:
  build: # this can be any name you choose
    docker:
      - image: node:20-bullseye # Update to the latest stable Node.js version
    resource_class: large
    parallelism: 10

    steps:
      - checkout
      - restore_cache:
          name: Restore pnpm Package Cache
          keys:
            - pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
      - run:
          name: Install pnpm package manager
          command: |
            corepack enable
            corepack prepare pnpm@latest --activate # Ensure latest pnpm version
      - run:
          name: Install Dependencies
          command: |
            pnpm install
      - save_cache:
          name: Save pnpm Package Cache
          key: pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
          paths:
            - node_modules
      - run:
          name: Build
          command: |
            pnpm build

workflows:
  build_test:
    jobs:
      - build
